apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mediawiki
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mediawiki
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: mediawiki
        image: mediawiki
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    appProtocol: http
  selector:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/component: frontend
  type: LoadBalancer
