apiVersion: v1
kind: Pod
metadata:
  name: dev-machine
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: dev-machine
  restartPolicy: Always