apiVersion: v1
kind: Service
metadata:
	name: full-deployment
spec:
	type: NodePort
	ports:
		- name: ssh
		  port: 22
		  nodePort: 30001
		  targetPort: dev-machine-ssh
	selector:
		app: dev-machine