apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: ghost
        image: ghost
        args:
          - -e
          - NODE_ENV=development
          - --name
          - some-ghost
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: 2368
    targetPort: 2368
    protocol: TCP
    appProtocol: http
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: frontend
  type: LoadBalancer
