apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-environ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: workstation
          image: ubuntu
          command:
            - "sleep"
            - "604800"
          ports:
            - containerPort: 22
        - name: dev-server
          image: ubuntu
          command:
            - "sleep"
            - "604800"
          ports:
            - containerPort: 80
            - containerPort: 22
        - name: prod-server
          image: ubuntu
          command:
            - "sleep"
            - "604800"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workstation-ssh
spec:
  ports:
    - name: ubuntu
      protocol: TCP
      port: 22
---
apiVersion: v1
kind: Service
metadata:
  name: dev-server-ports
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: ssh
      protocol: TCP
      port: 22
---
apiVersion: v1
kind: Service
metadata:
  name: prod-server-ports
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80