apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-1
  labels:
    type: dev-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/dev-pv-1